### ISSUE TITLE
Where to grab libpower_hardabi.a?

### ISSUE THREAD

**Issue by Nitori-** [nickray/lpc55s6x-hal#3]
I found a copy here, but I'm not sure if it's the right one (and my guess is they weren't actually supposed to upload it to GitHub): https://github.com/bluewind-embedded-systems/aws-nxp-lpc54018-demo/blob/master/NXP/libs/libpower_hardabi.a

I also needed to make this small substitution:

```
   Compiling lpc55s6x-hal v0.0.1 (/home/jwilcox/repo/lpc55s6x-hal)
error[E0412]: cannot find type `PIO1_6` in module `pins`
  --> examples/rtfm_led.rs:16:30
   |
16 | type RedLed = hal::Pin<pins::PIO1_6, states::pin_state::Gpio<states::gpio_state::direction::Output>>;
   |                              ^^^^^^
help: a struct with a similar name exists
   |
16 | type RedLed = hal::Pin<pins::Pio1_6, states::pin_state::Gpio<states::gpio_state::direction::Output>>;
   |                              ^^^^^^
help: possible candidate is found in another module, you can import it into scope
   |
6  | use lpc55s6x_pac::iocon::PIO1_6;
   |
```

Once I did those two things (and flashed the JLink firmware onto my board) the `rtfm_led` example worked great!

**Comment by Nitori-** [comment]
Ah nvm, I found it. Had to download the SDK for the board

**Comment by nickray** [comment]
Hi, yes it's in the SDK. Thank you for your interest @Nitori- ! Everything's still very much in flux, I'm trying to make things nicer than in most other HALs :))

I think I don't currently use this (currently closed source) static library, had just found reference to it in SDK setup code, while I was debugging USB device driver code. I should remove it as dependency agian.

Elsewhere I saw that NXP sometimes eventually releases the source, they seem scared of exposing undocumented registers which can brick the chip.
